<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://service.org" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://service.org" xmlns:intf="http://service.org" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://service.org" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getProducts">
    <complexType/>
   </element>
   <element name="getProductsResponse">
    <complexType>
     <sequence>
      <element name="getProductsReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="getProductsRequest">

      <wsdl:part element="impl:getProducts" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getProductsResponse">

      <wsdl:part element="impl:getProductsResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="ProductCatalog">

      <wsdl:operation name="getProducts">

         <wsdl:input message="impl:getProductsRequest" name="getProductsRequest">

       </wsdl:input>

         <wsdl:output message="impl:getProductsResponse" name="getProductsResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="ProductCatalogSoapBinding" type="impl:ProductCatalog">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getProducts">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getProductsRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getProductsResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="ProductCatalogService">

      <wsdl:port binding="impl:ProductCatalogSoapBinding" name="ProductCatalog">

         <wsdlsoap:address location="http://localhost:8080/TestMart/services/ProductCatalog"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
